# Generated by Django 6.0.7 on 2026-07-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_collaboration_invitation'),
        ('blogs', '0007_comment_parent'),
    ]

    operations = [
    ]
