# Generated by Django 6.0.7 on 2026-07-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_transferrequest_is_notified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferrequest',
            old_name='is_notified',
            new_name='requester_notified',
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='target_notified',
            field=models.BooleanField(default=False),
        ),
    ]
